# Generated by Django 4.0.5 on 2023-06-29 09:06

import datetime
from django.db import migrations, models
from datetime import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecEntrega',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 9, 6, 55, 930920, tzinfo=timezone.utc)),
        ),
    ]
